#!/bin/python3

import os
import re
import unicodedata

from config import CHAR_HEIGHT
from unicode_blocks import parse_unicode_path

INPUT_DIR = "glyphs"
OUTPUT_FILE = "cozette_txt.bfd"

# Glyphs whose right edge exceed this column are double width
WIDE_GLYPH_THRESHOLD = 9

# Scalable width associated to each device width
SWIDTHS = {0: 0, 6: 500, 12: 922}

PROPERTIES = """STARTFONT 2.1
FONT -samhain-Cozette-Medium-R-Normal--13-120-75-75-M-60-ISO10646-1
SIZE 12 75 75
FONTBOUNDINGBOX 14 15 -1 -3
COMMENT "Generated by fontforge, http://fontforge.sourceforge.net"
COMMENT "(c) 2020-2026 Samhain <samhain@moonwit.ch> & contributors <https://github.com/the-moonwitch/Cozette/contributors>"
STARTPROPERTIES 40
FOUNDRY "samhain"
FAMILY_NAME "Cozette"
WEIGHT_NAME "Medium"
SLANT "R"
SETWIDTH_NAME "Normal"
ADD_STYLE_NAME ""
PIXEL_SIZE 13
POINT_SIZE 120
RESOLUTION_X 75
RESOLUTION_Y 75
SPACING "M"
AVERAGE_WIDTH 60
CHARSET_REGISTRY "ISO10646"
CHARSET_ENCODING "1"
FONTNAME_REGISTRY ""
FONT_NAME "Cozette"
FACE_NAME "Cozette"
COPYRIGHT "(c) 2020-2026 Samhain <samhain@moonwit.ch> & contributors <https://github.com/the-moonwitch/Cozette/contributors>"
FONT_VERSION "2.000"
FONT_ASCENT 10
FONT_DESCENT 3
UNDERLINE_POSITION -19
UNDERLINE_THICKNESS 13
X_HEIGHT 5
CAP_HEIGHT 7
DEFAULT_CHAR 0
RAW_ASCENT 769
RAW_DESCENT 230
NORM_SPACE 6
RELATIVE_WEIGHT 50
RELATIVE_SETWIDTH 50
SUPERSCRIPT_X 0
SUPERSCRIPT_Y 2
SUPERSCRIPT_SIZE 2
SUBSCRIPT_X 0
SUBSCRIPT_Y 2
SUBSCRIPT_SIZE 2
FIGURE_WIDTH 6
AVG_LOWERCASE_WIDTH 60
AVG_UPPERCASE_WIDTH 60
ENDPROPERTIES
"""


def read_glyphs(dir: str) -> list[tuple[int, str, str]]:
    glyphs = []

    for root, _, files in os.walk(dir, topdown=False):
        for name in files:
            path = os.path.join(root, name)

            with open(path) as glyph:
                glyph_txt = glyph.read()
                (codepoint, start_char_name) = parse_unicode_path(path)
                glyphs.append((codepoint, start_char_name, glyph_txt))

    return glyphs


def device_width(codepoint: int, has_pixels: bool, right_edge: int) -> int:
    """Guess the BDF DWIDTH of a glyph"""
    char = chr(codepoint)
    if unicodedata.east_asian_width(char) == "F":
        return 12

    # Blank glyphs are zero width, except spaces and control chars
    if not has_pixels:
        return 6 if unicodedata.category(char) in ("Zs", "Zl", "Cc") else 0

    return 12 if right_edge >= WIDE_GLYPH_THRESHOLD else 6


def make_glyph(output, codepoint: int, start_char_name: str, glyph_txt: str):
    """Add a glyph to the output BDF file"""

    additional_offset = (0, 0)
    additional_offset_match = re.search(r"@offset=(-?\d+),(-?\d+);", glyph_txt)
    if additional_offset_match is not None:
        additional_offset = (
            int(additional_offset_match.group(1)),
            int(additional_offset_match.group(2)),
        )

    bitmap_txt = glyph_txt.split(";")[-1].split("\n")

    # Compute the glyph bounding box

    # Remove blank lines before bitmap
    top_blank_lines = 0
    while len(bitmap_txt) > 1 and len(bitmap_txt[0].strip()) == 0:
        top_blank_lines += 1
        bitmap_txt = bitmap_txt[1:]

    # Remove blank lines after bitmap
    while len(bitmap_txt) > 1 and len(bitmap_txt[-1].strip()) == 0:
        bitmap_txt = bitmap_txt[:-1]

    bounding_height = len(bitmap_txt)

    horizontal_offset = 999  # TODO: How to manage this ?
    max_width = 0
    for line in bitmap_txt:
        first_pixel = line.find("#")
        last_pixel = line.rfind("#")
        if first_pixel != -1:
            horizontal_offset = min(horizontal_offset, first_pixel)

        if last_pixel != -1:
            max_width = max(max_width, last_pixel)

    # There is no pixel at all in this glyph
    has_pixels = horizontal_offset != 999
    if not has_pixels:
        horizontal_offset = 0

    bounding_width = max_width - horizontal_offset + 1

    vertical_offset = CHAR_HEIGHT - bounding_height - top_blank_lines - 3

    # Remove blank chars used as offset, and pad every row to the bounding
    # width so that each row is encoded with the same number of bytes
    bitmap_txt = list(map(
        lambda x: x[horizontal_offset:][:bounding_width].ljust(bounding_width),
        bitmap_txt,
    ))

    horizontal_offset += additional_offset[0]
    # Textual offsets go downwards, while BDF offsets go upwards
    vertical_offset -= additional_offset[1]

    # Blank glyphs are a single unlit pixel, its position doesn't matter
    if not has_pixels:
        horizontal_offset = 0
        vertical_offset = 0

    output.write(f"STARTCHAR {start_char_name}\n")
    output.write(f"ENCODING {codepoint}\n")
    dwidth = device_width(
        codepoint, has_pixels, max_width + 1 + additional_offset[0]
    )
    output.write(f"SWIDTH {SWIDTHS.get(dwidth, 500)} 0\n")
    output.write(f"DWIDTH {dwidth} 0\n")
    output.write(f"BBX {bounding_width} {bounding_height}")
    output.write(f" {horizontal_offset} {vertical_offset}\n")
    output.write("BITMAP\n")

    for line in bitmap_txt:
        for chunk in [
            line[chunk : chunk + 8] for chunk in range(0, bounding_width, 8)
        ]:
            encoded = 0
            for i, c in enumerate(chunk):
                encoded |= (c == "#") << (7 - i)

            output.write(f"{encoded:02x}".upper())

        output.write("\n")

    output.write("ENDCHAR\n")


def main():
    with open(OUTPUT_FILE, "w") as output:
        glyphs = read_glyphs(INPUT_DIR)

        # Sort glyphs using their codepoint
        glyphs.sort(key=lambda x: x[0])

        output.write(PROPERTIES)
        output.write(f"CHARS {len(glyphs)}\n")

        for glyph in glyphs:
            make_glyph(output, *glyph)

        output.write("ENDFONT\n")


if __name__ == "__main__":
    main()
